- name: Install aptitude using apt
  apt:
    name: aptitude
    state: latest
    update_cache: true

- name: Install system packages
  apt:
    state: latest
    update_cache: true
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python3
    - python3-pip
    - python-setuptools

- name: Add Docker GPG Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install docker-ce
  apt:
    state: latest
    update_cache: true
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Start docker service
  service:
    name: docker
    state: started

- name: pip docker
  pip:
    executable: pip3
    name: docker

- name: Create Sudo User
  user: 
    name: docker
    groups: sudo
    shell: /bin/bash
    generate_ssh_key: no
    state: present