pipeline{
    agent any
    environment{
        DATABASE_URI = credentials("DATABASE_URI")
        AUTHOR = credentials("AUTHOR")
    }
    stages{
        stage("Testing"){
            steps{
                sh "bash Jenkins/test_script.sh"
            }
        }
        stage("Build & Push"){
            steps{
                sh "bash Jenkins/build_push.sh"
            }
        }
        stage("Config Management (ansible)"){
            steps{
                sh "bash Jenkins/config_ansible.sh"
            }
        }
        stage("Deploy"){
            steps{
                sh "bash Jenkins/deploy_stack.sh" 
            }
        }
    }
    post{
        always{
            junit "**/junit.xml"
            cobertura coberturaReportFile: '**/coverage.xml', failNoReports: false, failUnstable: false, onlyStable: false
        }
    }
}